#ifndef VANEDB_RS_CAPI_H
#define VANEDB_RS_CAPI_H

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct VectorStore VectorStore;
typedef struct HnswIndex HnswIndex;
typedef struct MmapVectorStore MmapVectorStore;


#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 * `a` and `b` must each point to at least `dim` valid `f32` values.
 */
float vanedb_rs_l2_sq(const float *a, const float *b, uintptr_t dim);

/**
 * # Safety
 * `a` and `b` must each point to at least `dim` valid `f32` values.
 */
float vanedb_rs_cosine_distance(const float *a, const float *b, uintptr_t dim);

/**
 * # Safety
 * `a` and `b` must each point to at least `dim` valid `f32` values.
 */
float vanedb_rs_dot_product(const float *a, const float *b, uintptr_t dim);

/**
 * # Safety
 * Safe to call with any arguments; returns an owning handle (or null on error)
 * that must eventually be freed with `vanedb_rs_store_free`.
 */
VectorStore *vanedb_rs_store_new(uintptr_t dim, uint32_t metric);

/**
 * # Safety
 * `s` must be a live handle from `vanedb_rs_store_new` (or null), and
 * `v` must point to at least `dim` valid `f32` values (where `dim` matches the store).
 */
int32_t vanedb_rs_store_add(VectorStore *s, uint64_t id, const float *v);

/**
 * # Safety
 * `s` must be a live handle from `vanedb_rs_store_new` (or null); `ids` must point to
 * `n` valid `u64`s and `vecs` to `n * dim` valid `f32`s (both may be null when `n` is 0).
 * All-or-nothing: on error (duplicate id, length mismatch) the store is unchanged.
 */
int32_t vanedb_rs_store_add_batch(VectorStore *s,
                                  const uint64_t *ids,
                                  const float *vecs,
                                  uintptr_t n);

/**
 * # Safety
 * `s` must be a live handle from `vanedb_rs_store_new` (or null); `q` must point to
 * `dim` valid `f32`s; `out_ids` and `out_dists` must each have room for `k` elements.
 */
uintptr_t vanedb_rs_store_search(VectorStore *s,
                                 const float *q,
                                 uintptr_t k,
                                 uint64_t *out_ids,
                                 float *out_dists);

/**
 * # Safety
 * The handle must have come from `vanedb_rs_store_new` and not been freed already
 * (or be null, which is a no-op).
 */
void vanedb_rs_store_free(VectorStore *s);

/**
 * # Safety
 * Safe to call with any arguments; returns an owning handle (or null on error)
 * that must eventually be freed with `vanedb_rs_hnsw_free`.
 */
HnswIndex *vanedb_rs_hnsw_new(uintptr_t dim,
                              uint32_t metric,
                              uintptr_t capacity,
                              uintptr_t m,
                              uintptr_t ef_construction,
                              uint64_t seed);

/**
 * # Safety
 * `h` must be a live handle from `vanedb_rs_hnsw_new` (or null), and
 * `v` must point to at least `dim` valid `f32` values (where `dim` matches the index).
 */
int32_t vanedb_rs_hnsw_add(HnswIndex *h, uint64_t id, const float *v);

/**
 * # Safety
 * `h` must be a live handle from `vanedb_rs_hnsw_new` (or null); `ids` must point to
 * `n` valid `u64`s and `vecs` to `n * dim` valid `f32`s (both may be null when `n` is 0).
 * All-or-nothing: on error (duplicate id, capacity, length mismatch) the index is unchanged.
 */
int32_t vanedb_rs_hnsw_add_batch(HnswIndex *h, const uint64_t *ids, const float *vecs, uintptr_t n);

/**
 * # Safety
 * `h` must be a live handle from `vanedb_rs_hnsw_new` (or null); `q` must point to
 * `dim` valid `f32`s; `out_ids` and `out_dists` must each have room for `k` elements.
 */
uintptr_t vanedb_rs_hnsw_search(HnswIndex *h,
                                const float *q,
                                uintptr_t k,
                                uintptr_t ef_search,
                                uint64_t *out_ids,
                                float *out_dists);

/**
 * # Safety
 * `h` must be a live handle from `vanedb_rs_hnsw_new` (or null);
 * `path` must be a valid NUL-terminated C string.
 */
int32_t vanedb_rs_hnsw_save(HnswIndex *h, const char *path);

/**
 * # Safety
 * `path` must be a valid NUL-terminated C string. Returns an owning handle (or null)
 * that must be freed with `vanedb_rs_hnsw_free`.
 */
HnswIndex *vanedb_rs_hnsw_load(const char *path);

/**
 * # Safety
 * The handle must have come from `vanedb_rs_hnsw_new` or `vanedb_rs_hnsw_load`
 * and not been freed already (or be null, which is a no-op).
 */
void vanedb_rs_hnsw_free(HnswIndex *h);

/**
 * # Safety
 * `path` must be a valid NUL-terminated C string; `ids` must point to `n` valid `u64`s;
 * `vecs` must point to `n * dim` valid `f32`s.
 */
int32_t vanedb_rs_mmap_build(const char *path,
                             uintptr_t dim,
                             uint32_t metric,
                             const uint64_t *ids,
                             const float *vecs,
                             uintptr_t n);

/**
 * # Safety
 * `path` must be a valid NUL-terminated C string. Returns an owning handle (or null)
 * that must be freed with `vanedb_rs_mmap_free`.
 */
MmapVectorStore *vanedb_rs_mmap_open(const char *path);

/**
 * # Safety
 * `m` must be a live handle from `vanedb_rs_mmap_open` (or null); `q` must point to
 * `dim` valid `f32`s; `out_ids` and `out_dists` must each have room for `k` elements.
 */
uintptr_t vanedb_rs_mmap_search(MmapVectorStore *m,
                                const float *q,
                                uintptr_t k,
                                uint64_t *out_ids,
                                float *out_dists);

/**
 * # Safety
 * The handle must have come from `vanedb_rs_mmap_open` and not been freed already
 * (or be null, which is a no-op).
 */
void vanedb_rs_mmap_free(MmapVectorStore *m);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VANEDB_RS_CAPI_H */
