"""Type stubs for vanedb.

The runtime surface is a compiled PyO3 extension, so these stubs are what an
editor and a type checker see. `tests/test_type_stubs.py` asserts they match
the runtime module, because a stub that drifts is worse than no stub.
"""

from typing import Any, TypeAlias

__version__: str
__all__: list[str]

# Shape and dtype are validated at runtime, so these aliases document the
# accepted forms rather than constraining them — a checker cannot verify that
# a numpy array is 2-D float32.

#: A 1-D float32 buffer (numpy array, array.array, memoryview) or any sequence
#: of floats, with length equal to the index dimension.
VectorLike: TypeAlias = Any

#: A 2-D float32 buffer of shape (n, dim), or a sequence of float sequences.
BatchLike: TypeAlias = Any

#: A 1-D uint64 or int64 buffer, or a sequence of ints. Negative ids raise
#: ValueError.
IdsLike: TypeAlias = Any

class Metric:
    """Distance metric for vector comparison."""

    L2: Metric
    COSINE: Metric
    DOT: Metric

class FlatIndex:
    """Exact k-NN by brute-force scan. Thread-safe."""

    def __init__(self, dim: int, metric: Metric = ...) -> None: ...
    @property
    def metric(self) -> Metric: ...
    @property
    def dimension(self) -> int: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def add(self, id: int, vector: VectorLike) -> None: ...
    def add_batch(self, ids: IdsLike, vectors: BatchLike) -> None: ...
    def get(self, id: int) -> list[float]: ...
    def get_vector(self, id: int) -> list[float]: ...
    def contains(self, id: int) -> bool: ...
    def remove(self, id: int) -> None: ...
    def search(self, query: VectorLike, k: int) -> list[tuple[int, float]]: ...

class ApproxIndex:
    """Approximate k-NN over an HNSW graph, with persistence."""

    def __init__(
        self,
        dim: int,
        metric: Metric = ...,
        capacity: int = ...,
        m: int = ...,
        ef_construction: int = ...,
        seed: int = ...,
    ) -> None: ...
    @property
    def metric(self) -> Metric: ...
    @property
    def dimension(self) -> int: ...
    @property
    def capacity(self) -> int: ...
    @property
    def m(self) -> int: ...
    @property
    def ef_construction(self) -> int: ...
    @property
    def seed(self) -> int: ...
    @property
    def ef_search(self) -> int: ...
    @ef_search.setter
    def ef_search(self, ef: int) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def add(self, id: int, vector: VectorLike) -> None: ...
    def add_batch(self, ids: IdsLike, vectors: BatchLike) -> None: ...
    def upsert(self, id: int, vector: VectorLike) -> None: ...
    def get_vector(self, id: int) -> list[float]: ...
    def get(self, id: int) -> list[float]: ...
    def contains(self, id: int) -> bool: ...
    def remove(self, id: int) -> None: ...
    @property
    def tombstones(self) -> int: ...
    def compact(self) -> None: ...
    def search(
        self,
        query: VectorLike,
        k: int,
        *,
        ef_search: int | None = ...,
    ) -> list[tuple[int, float]]: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> ApproxIndex:
        """Raises FileNotFoundError if the file is absent, ValueError if corrupt."""

class DiskIndexBuilder:
    """Builds a file that DiskIndex can memory-map."""

    def __init__(self, dim: int, metric: Metric = ...) -> None: ...
    @property
    def dimension(self) -> int: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def add(self, id: int, vector: VectorLike) -> None: ...
    def save(self, path: str) -> None: ...

class DiskIndex:
    """Memory-mapped exact k-NN. Open with DiskIndex.open; not constructible.

    Keep the underlying file's contents and length unchanged in every process,
    from before open until the index is released. In-place modification can
    corrupt results or crash the interpreter. DiskIndexBuilder.save atomically
    replaces the path while leaving existing mappings intact.
    """

    @property
    def metric(self) -> Metric: ...
    @property
    def dimension(self) -> int: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def get(self, id: int) -> list[float]: ...
    def get_vector(self, id: int) -> list[float]: ...
    def contains(self, id: int) -> bool: ...
    def search(self, query: VectorLike, k: int) -> list[tuple[int, float]]: ...
    @staticmethod
    def open(path: str) -> DiskIndex:
        """Raises FileNotFoundError if the file is absent, ValueError if corrupt."""
